# Generated by Django 5.1.7 on 2025-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_blogpost_written_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="snippet",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="title",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Content (English)"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="Content (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_ro",
            field=models.TextField(default="", verbose_name="Content (Romanian)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="snippet_en",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Snippet (English)"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="snippet_es",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Snippet (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="snippet_ro",
            field=models.TextField(
                default="", max_length=500, verbose_name="Snippet (Romanian)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Title (English)"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_ro",
            field=models.CharField(
                default="", max_length=200, verbose_name="Title (Romanian)"
            ),
            preserve_default=False,
        ),
    ]
